### ISSUE TITLE
FYI: matrix builds

### ISSUE THREAD

**Issue by seriousme** [denoland/setup-deno#13]
Hi,

it might be convenient to document in the Readme how to test multiple versions using matrix builds, e.g.:

```yml
# This workflow will test on Deno lastest stable major and canary
# see https://github.com/marketplace/actions/setup-deno for details
name: Deno CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [vx.x.x, canary]
    steps:
    - uses: actions/checkout@v2
    - name: Use Deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
    - run: deno test
 ```

I have this working at https://github.com/seriousme/durable-data/blob/master/.github/workflows/deno-ci.yml

Kind regards,
Hans
