### ISSUE TITLE
Default to `v1.x`?

### ISSUE THREAD

**Issue by dsherret** [denoland/setup-deno#27]
Instead of writing:

```yaml
- uses: denoland/setup-deno@v1
  with:
    deno-version: v1.x
```

It would be nice to write:

```yaml
- uses: denoland/setup-deno@v1
```

Then when deno v2 is released we can bump the version of this action:

```yaml
- uses: denoland/setup-deno@v2
```

The one risk for this is if we would want to make any breaking changes to the action, but I feel we could just do that when a new major deno version release occurs.

This would not be a breaking change because not providing a `deno-version` currently errors.
