### ISSUE TITLE
Cache deno modules

### ISSUE THREAD

**Issue by jacque006** [denoland/setup-deno#31]
It would be nice if this action had a way to cache deno modules that had been downloaded in previous runs, similarly to https://github.com/actions/setup-node#caching-global-packages-data

The cache looks like it is easy enough to find https://deno.land/manual/linking_to_external_code#linking-to-third-party-code . However, I'm unsure what the key/hash for lookup and download would be to: 
- Determine if a module had changed in any file.
- Lookup existing module caches.

This part is easier with a NodeJS package manager such as `npm` or `yarn` as you can just use a hash of the lockfile.

**Comment by jespertheend** [comment]
I bet there's some way to do this using https://github.com/actions/cache, but I'm not sure what would be the right paths for `hashFiles()` and `path`

**Comment by GJZwiers** [comment]
> I bet there's some way to do this using https://github.com/actions/cache, but I'm not sure what would be the right paths for `hashFiles()` and `path`

It can be achieved by pointing `path` to the location of DENO_DIR and calling `hashFiles()` on the lockfile that is written with `deno cache --lock=<file> --lock-write`. For example:

```yaml
env:
  DENO_DIR: my_cache_directory

steps:
  - name: Cache Deno dependencies 
    uses: actions/cache@v2
    with:
      path: ${{ env.DENO_DIR }}
      key: ${{ hashFiles('lock.json') }}
```

Having an option in setup_deno to cache could be useful, although there is perhaps more diversity in what lockfile names people use compared to Node where it's almost always `package-lock.json`, `npm-shrinkwrap.json` or `yarn.lock`.

**Comment by csvn** [comment]
This would be greatly appreciated. It would streamline action setup a lot to not have to manually setup `actions/cache`.

**Comment by joshdales** [comment]
Just discovered that there are also examples in `actions/cache` of setting it up with Deno https://github.com/actions/cache/blob/main/examples.md#deno. Thought I would share in case others come looking for more examples. 

Though I agree with others that it would be nice if it was part of the deno action.

**Comment by csvn** [comment]
I've created a PR for this now: #89. Unfortunately, `@actions/cache` is a package with a lot of dependencies, and the checked in `/node_modules` would become huge if it's just installed as-is.

![image](https://github.com/user-attachments/assets/f68c95b6-cb11-404c-b705-1fb812da2dc5)

I've opened the PR to get feedback. Perhaps the Deno team will just accept installing the dependencies and pushing them to the branch, or it might be required to add a build-step (similar to `@actions/setup-node`) to bundle everything into one file.

Hopefully, it should be possible to do something like below if the PR get's merged, and save a ton of boilerplate.

```yml
# Before
env:
  DENO_DIR: ${{ github.workspace }}/.deno

      - uses: denoland/setup-deno@v2
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: ${{ env.DENO_DIR }}
          key: cache-${{ runner.os }}-test-${{ hashFiles('deno.lock') }}
          restore-keys: cache-${{ runner.os }}
      - run: deno run -A npm:cowsay Hello!
      - uses: actions/cache/save@v4
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ steps.cache.outputs.cache-primary-key }}
```

```yml
# After
      - uses: denoland/setup-deno@v2
        with:
          cache: true
          cache-hash: ${{ hashFiles('deno.lock') }}
      - run: deno run -A npm:cowsay Hello!
```
