### ISSUE TITLE
Support .dvmrc

### ISSUE THREAD

**Issue by BrunoBernardino** [denoland/setup-deno#32]
I personally use a `.dvmrc` file to keep track of the deno version used for that specific repo/project, so it would be helpful to have the possibility to have the action read that instead of having to update in two places.

This is supported by `actions/setup-node`, like:

```yml
  - name: Setup node
    uses: actions/setup-node@v2
    with:
      node-version-file: '.nvmrc'
```

So it could be supported with something like:

```yml
  - name: Setup Deno
    uses: denoland/setup-deno@v1
    with:
      deno-version-file: '.dvmrc'
```
