### ISSUE TITLE
setup-deno can't work on Actions with Ubuntu

### ISSUE THREAD

**Issue by Comamoca** [denoland/setup-deno#40]
Hello!

I tried with [nektos/act](https://github.com/nektos/act) locally, but setup-deno failed.
Actions Setting:
```yaml
name: CI
on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    name: Deno CI
    steps:
      - uses: actions/checkout@master
      - name: Setup Deno
        uses: denolib/setup-deno@v1.1.0
        with:
          deno-version: "1.28.0"
      - run: deno run https://deno.land/std/examples/welcome.ts
```
I saw this log, see this image.
![image](https://user-images.githubusercontent.com/93137338/204135705-0e7d4546-2430-4f7a-9f52-0b8c9c644e20.png)

How do dissolution this error? Thank you.
