### ISSUE TITLE
Action is broken on latest version(s)

### ISSUE THREAD

**Issue by GJZwiers** [denoland/setup-deno#43]
The setup-deno action does not work on the latest Deno version(s)

```
Run denoland/setup-deno@v1.1.1
Error: TypeError: fetch failed
```

```yaml
  - uses: actions/checkout@v3
  - uses: denoland/setup-deno@v1.1.1
    with:
      deno-version: v1.x
```
