### ISSUE TITLE
Error: Unable to resolve action `denoland/setup-deno@1.1.4`, unable to find version `1.1.4`

### ISSUE THREAD

**Issue by ebanDev** [denoland/setup-deno#59]
Hello ! 

I'm tryna use this github action for my project, but I get this error : 

Error: Unable to resolve action `denoland/setup-deno@1.1.4`, unable to find version `1.1.4`

This is strange because i'm really using the simplest workflow file you could imagine and I can't figure out why this bug is happening 

```
name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@1.1.4
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint
```

You can find the full source code here :

https://github.com/ebanDev/ent-cookies/

Thank you ! :)
Eban
