### ISSUE TITLE
Deno compile workflow not running

### ISSUE THREAD

**Issue by MBeggiato** [denoland/setup-deno#88]
Hi,
I want to use Github Actions with Deno 2 to automaticaly compile to a executable. I got the workflow setup but now recive the 
following error in the compile step:

`Run deno compile --allow-write --allow-read --target x86_64-pc-windows-msvc --icon ./icon.ico --output ./build/windows/ConventionalFighter.exe main.ts`
  
`Download https://registry.npmjs.org/keypress`
`Check file:///D:/a/ConventionalFighter/ConventionalFighter/main.ts`
`Compile file:///D:/a/ConventionalFighter/ConventionalFighter/main.ts to ./build/windows/ConventionalFighter.exe`
`Download https://dl.deno.land/release/v2.0.3/denort-x86_64-pc-windows-msvc.zip`
`error: Writing deno compile executable to temporary file './build/windows\ConventionalFighter.exe.tmp-0b65dea24cd6b2cb'`
`Caused by:`
`    The system cannot find the file specified. (os error 2)`
`Error: Process completed with exit code 1.`

My workflow steps looks like this:
```
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0

      - name: Build for Windows
        run: deno compile --allow-write --allow-read --target x86_64-pc-windows-msvc --icon ./icon.ico --output ./build/windows/ConventionalFighter.exe main.ts

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ConventionalFighter-Windows
          path: ./build/windows/ConventionalFighter.exe
```

**Comment by mactkg** [comment]
I also encountered same issue on my new project [mactkg/st](https://github.com/mactkg/st).
I try to create small reproduce project, but somehow I can't.
(You can see logs trying reproduce the issue at https://github.com/mactkg-playground/deno-compile-on-gh-repro/actions )

@MBeggiato You can see my code on https://github.com/mactkg/st. Could you find same things between your and my codebase? It may help to find causes.

**Comment by mactkg** [comment]
I made more time to reproduce this issue and finally found the smallest reproduction project.
I can't find the root cause, but it fails when an unused _npm_ package is written in the `deno.lock` / `deno.json` file.

- There is a `npm:cowsay` package in deno.json / deno.lock
  - https://github.com/mactkg-playground/deno-compile-on-gh-repro/blob/main/deno.json#L3
  - https://github.com/mactkg-playground/deno-compile-on-gh-repro/blob/main/deno.lock#L4
- But a code doesn't use the package 
  - https://github.com/mactkg-playground/deno-compile-on-gh-repro/blob/main/main.ts
- The workflow is successful if the package is used in `main.ts`.
  - https://github.com/mactkg-playground/deno-compile-on-gh-repro/commit/4b7fcaee6c99cd08b0db4dd2e62a9d4e29f0dff0

@MBeggiato Does it help you?

**Comment by im28** [comment]
when adding this to my workflow I was able to get it to work,

```yaml
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
```
