### ISSUE TITLE
Deno v2.2.5 is not available

### ISSUE THREAD

**Issue by hugoalh** [denoland/setup-deno#93]
[Deno v2.2.5 is released at 2025-03-21](https://github.com/denoland/deno/releases/tag/v2.2.5), which should be available as of written.

However if the workflow is like this:

```yml
...
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v2"
        with:
          deno-version: "^2.2.5"
...
```

Then it has this result: ([Example](https://github.com/hugoalh/deno-lint-rules/actions/runs/14098149878/job/39490047735#step:3:8))

```
...
Run denoland/setup-deno@v2
  with:
    deno-version: ^2.2.5
    deno-binary-name: deno
Error: Could not resolve a version for the given range.
```

If the workflow change the `deno-version` to this:

```yml
...
      - name: "Setup Deno"
        uses: "denoland/setup-deno@v2"
        with:
          deno-version: "^2.2.0"
...
```

Then it resolve to v2.2.4:

```
...
Run denoland/setup-deno@v2
  with:
    deno-version: ^2.2.0
    deno-binary-name: deno
Going to install stable version 2.2.4.
Downloading Deno from https://github.com/denoland/deno/releases/download/v2.2.4/deno-x86_64-unknown-linux-gnu.zip.
/usr/bin/unzip -o -q /home/runner/work/_temp/0f18169e-756c-41be-8226-3c2201aa1099
Cached Deno to /opt/hostedtoolcache/deno/2.2.4/x64.
Installation complete.
...
```
