### ISSUE TITLE
Cannot install latest version of deno

### ISSUE THREAD

**Issue by soundstep** [denoland/setup-deno#96]
<img width="477" alt="Image" src="https://github.com/user-attachments/assets/c275b942-d655-4242-8a45-4c23e69ebd03" />

With

```yaml
- uses: denoland/setup-deno@v2
  with:
    deno-version: v2.11.x
```

I'll try run a `deno upgrade` for now.
